name: solidart_translator_example
description: "solidart_translator example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^2.0.0
  example_translations:
    path: ../../../tool/example_translations
  flutter_solidart: ^2.7.4
  solidart_translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.6
  translator_conformance:
    path: ../../../tool/translator_conformance

flutter:
  uses-material-design: true
