# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub"
    directories:
      - "/packages/signals_translator_core"
      - "/packages/signals_translator"
      - "/packages/signals_translator/example"
      - "/packages/alien_signals_translator"
      - "/packages/alien_signals_translator/example"
      - "/packages/solidart_translator"
      - "/packages/solidart_translator/example"
    schedule:
      interval: "weekly"
