name: signals_translator
description: "Translate your project 100% using signals"
version: 0.0.2
homepage: https://github.com/nathantaal/flutter-signals-translator
repository: https://github.com/nathantaal/flutter-signals-translator

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  signals: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0